apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: convertx-externalsecrets
  # namespace: NOTREQUIREDINSIDECHART
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  data:
    - secretKey: convertx-jwt-secret
      remoteRef:
        key: "81abf074-4f0f-4793-8102-b3c2002f98b9"
