apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: keycloak-operator

namespace: keycloak
resources:
  - https://raw.githubusercontent.com/keycloak/keycloak-k8s-resources/26.5.1/kubernetes/kubernetes.yml

