
# https://github.com/iib0011/omni-tools
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: omni-tools
  name: omni-tools
#  namespace: omni-tools
spec:
  selector:
    matchLabels:
      app: omni-tools
  template:
    metadata:
      labels:
        app: omni-tools
        app.kubernetes.io/name: omni-tools # required for Homepage
    spec:
      containers:
        - name: omni-tools
          # https://github.com/omni-tools-app/omni-tools/pkgs/container/omni-tools 
          image: iib0011/omni-tools:latest
          imagePullPolicy: Always
          env:
            # - name: PUID
            #   value: "1000"
            # - name: PGID
            #   value: "1000"
            - name: TZ
              value: "Australia/Sydney"
          ports:
            - containerPort: 80
              name: omni-tools-http
              protocol: TCP
          resources:
            requests:
              cpu: 250m
              memory: 750Mi
            limits:
              cpu: "1000m"
              memory: "2000Mi"
          livenessProbe:
            httpGet:
              path: /
              port: omni-tools-http
          readinessProbe:
            httpGet:
             path: /
             port: omni-tools-http
          startupProbe:
            httpGet:
              path: /
              port: omni-tools-http
            failureThreshold: 30
---
apiVersion: v1
kind: Service
metadata:
  name: omni-tools-http-svc
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: omni-tools-http
  selector:
    app: omni-tools
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    #acme.cert-manager.io/http01-ingress-class: nginx-external
    #kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-dns01-prod"
    #cert-manager.io/cluster-issuer: "letsencrypt-staging"
    kubernetes.io/ingress.class: "nginx"
    #acme.cert-manager.io/http01-ingress-class: "nginx-external"
    #nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    #nginx.org/ssl-services: "tvheadend-http-svc"
    nginx.org/websocket-services: "omni-tools-http-svc"        
    nginx.org/proxy-read-timeout: "3600"
    nginx.org/proxy-send-timeout: "3600" 
    nginx.ingress.kubernetes.io/proxy-body-size: "100m" # allow uploads (aka backups) of up to 100MB
    gethomepage.dev/description: Variety of online tools to simplify everyday tasks
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: Productivity
    gethomepage.dev/icon: https://raw.githubusercontent.com/iib0011/omni-tools/main/public/favicon.png
    gethomepage.dev/name: OmniTools

  name: omni-tools
spec:
  rules:
    - host: omni-tools.rockyroad.rocks
      http:
        paths:
          - backend:
              service:
                name: omni-tools-http-svc
                port:
                  number: 80
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - omni-tools.rockyroad.rocks
      secretName: omni-tools-tls
---