
# Example chart: https://github.com/dixneuf19/brassberry-gitops/blob/main/spliit/spliit/values.yaml
#                https://github.com/dixneuf19/brassberry-gitops/blob/main/spliit/spliit/templates/manifests.yaml

--- # deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: spliit
  name: spliit
#  namespace: spliit
spec:
  selector:
    matchLabels:
      app: spliit
  template:
    metadata:
      labels:
        app: spliit
        app.kubernetes.io/name: spliit # required for Homepage
    spec:
      containers:
        - name: spliit
          # https://github.com/spliit-app/spliit/pkgs/container/spliit 
          image: ghcr.io/spliit-app/spliit:1.19.0
          imagePullPolicy: Always
          env:
            # - name: PUID
            #   value: "1000"
            # - name: PGID
            #   value: "1000"
            - name: TZ
              value: "Australia/Sydney"
            # - name: POSTGRES_HOST
            #   value: "postgres-service"
            # - name: POSTGRES_NAME
            #   value: "spliit"
            # - name: POSTGRES_USER
            #   value: "spliit-user"
            # - name: POSTGRES_PASSWORD
            #   valueFrom:
            #     secretKeyRef:
            #       name: spliit-externalsecrets
            #       key: spliit-postgres-secret
            - name: POSTGRES_PRISMA_URL
              # value: "postgresql://postgres:${POSTGRES_PASSWORD}@db"
              valueFrom:
                secretKeyRef:
                  name: spliit-externalsecrets
                  key: spliit-postgres-url # templated by external secrets
            - name: POSTGRES_URL_NON_POOLING
              # value: "postgresql://postgres:${POSTGRES_PASSWORD}@db"
              valueFrom:
                secretKeyRef:
                  name: spliit-externalsecrets
                  key: spliit-postgres-url # templated by external secrets
            - name: POSTGRES_TIMEOUT
              value: "60"
          ports:
            - containerPort: 3000
              name: spliit-http
              protocol: TCP
          resources:
            requests:
              cpu: 250m
              memory: 750Mi
            limits:
              cpu: "1000m"
              memory: "2000Mi"
          livenessProbe:
            httpGet:
              path: /api/health/liveness
              port: spliit-http
          readinessProbe:
            httpGet:
             path: /api/health/readiness
             port: spliit-http
          startupProbe:
            httpGet:
              path: /api/health/readiness
              port: spliit-http
            failureThreshold: 30
---
apiVersion: v1
kind: Service
metadata:
  name: spliit-http-svc
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: spliit-http
  selector:
    app: spliit
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    #acme.cert-manager.io/http01-ingress-class: nginx-external
    #kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-dns01-prod"
    #cert-manager.io/cluster-issuer: "letsencrypt-staging"
    kubernetes.io/ingress.class: "nginx"
    #acme.cert-manager.io/http01-ingress-class: "nginx-external"
    #nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    #nginx.org/ssl-services: "tvheadend-http-svc"
    nginx.org/websocket-services: "spliit-http-svc"        
    nginx.org/proxy-read-timeout: "3600"
    nginx.org/proxy-send-timeout: "3600" 
    nginx.ingress.kubernetes.io/proxy-body-size: "100m" # allow uploads (aka backups) of up to 100MB
    gethomepage.dev/description: spliit
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: Lifestyle
    gethomepage.dev/icon: https://raw.githubusercontent.com/spliit-app/spliit/refs/heads/main/public/logo.svg
    gethomepage.dev/name: spliit

  name: spliit
spec:
  rules:
    - host: spliit.rockyroad.rocks
      http:
        paths:
          - backend:
              service:
                name: spliit-http-svc
                port:
                  number: 80
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - spliit.rockyroad.rocks
      secretName: spliit-tls
---