apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mealie-externalsecrets
  # namespace: NOTREQUIREDINSIDECHART
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  data:
    - secretKey: mealie-postgres-password
      remoteRef:
        key: "f447c9f9-295f-4442-9547-b37800a7a3a4"
    - secretKey: mealie-openai-key
      remoteRef:
        key: "fbb55cae-cbfa-43a5-a658-b3d800084013"
    - secretKey: mealie-oidc-client-secret
      remoteRef:
        key: "c3169206-9bfb-4724-9617-b3db001ce1ab"
